// GENERATED by packages/vod/scripts/gen-models.py from the BytePlus Python
// SDK (byteplussdkvod20250701 attribute_map + swagger_types). Do not edit by
// hand; re-run the generator. Enforces decision 0100 (wire is PascalCase,
// keep everything, no passthrough).

export interface GetExecutionRequest {
  runId: string;
}

export interface GetExecutionResponse {
  code?: string;
  control?: ControlForGetExecutionOutput;
  input?: InputForGetExecutionOutput;
  meta?: MetaForGetExecutionOutput;
  operation?: OperationForGetExecutionOutput;
  output?: OutputForGetExecutionOutput;
  runId?: string;
  status?: string;
}

export interface AudioStreamMetaForGetExecutionOutput {
  bitrate?: number;
  codec?: string;
  duration?: number;
  quality?: string;
  sampleRate?: number;
}

export interface ControlForGetExecutionOutput {
  callbackArgs?: string;
  clientToken?: string;
  priority?: number;
}

export interface ConvertEnhanceForGetExecutionOutput {
  audioStreamMeta?: AudioStreamMetaForGetExecutionOutput;
  createTime?: string;
  duration?: number;
  dynamicRange?: string;
  encodedType?: string;
  encrypt?: boolean;
  encryption?: EncryptionForGetExecutionOutput;
  fileId?: string;
  fileType?: string;
  format?: string;
  logoType?: string;
  md5?: string;
  size?: number;
  storeUri?: string;
  tosStorageClass?: string;
  videoStreamMeta?: VideoStreamMetaForGetExecutionOutput;
}

export interface ConvertTaskForGetExecutionOutput {
  enhance?: ConvertEnhanceForGetExecutionOutput;
  type?: string;
}

export interface EncryptionForGetExecutionOutput {
  kid?: string;
}

export interface EnhanceForGetExecutionOutput {
  modules?: ModuleForGetExecutionOutput[];
  moeEnhance?: MoeEnhanceForGetExecutionOutput;
  type?: string;
}

export interface InputForGetExecutionOutput {
  type?: string;
  vid?: string;
}

export interface MetaForGetExecutionOutput {
  createTime?: string;
  endTime?: string;
  spaceName?: string;
  startTime?: string;
  trigger?: string;
}

export interface ModuleForGetExecutionOutput {
  type?: string;
}

export interface MoeEnhanceForGetExecutionOutput {
  config?: string;
  target?: TargetForGetExecutionOutput;
  videoStrategy?: VideoStrategyForGetExecutionOutput;
}

export interface OperationForGetExecutionOutput {
  task?: TaskForGetExecutionOutput;
  type?: string;
}

export interface OutputForGetExecutionOutput {
  task?: ConvertTaskForGetExecutionOutput;
  type?: string;
}

export interface TargetForGetExecutionOutput {
  bitrate?: number;
  fps?: number;
  res?: string;
  resLimit?: number;
  scaleRatio?: number;
}

export interface TaskForGetExecutionOutput {
  enhance?: EnhanceForGetExecutionOutput;
  type?: string;
}

export interface VideoStrategyForGetExecutionOutput {
  repairStrength?: number;
  repairStyle?: number;
}

export interface VideoStreamMetaForGetExecutionOutput {
  bitrate?: number;
  codec?: string;
  definition?: string;
  duration?: number;
  fps?: number;
  height?: number;
  width?: number;
}
