// GENERATED by packages/vod/scripts/gen-models.py from the BytePlus Python
// SDK (byteplussdkvod20250701 attribute_map + swagger_types). Do not edit by
// hand; re-run the generator. Enforces decision 0100 (wire is PascalCase,
// keep everything, no passthrough).

export interface StartExecutionRequest {
  control?: ControlForStartExecutionInput;
  input?: InputForStartExecutionInput;
  operation?: OperationForStartExecutionInput;
}

export interface StartExecutionResponse {
  runId?: string;
}

export interface ControlForStartExecutionInput {
  callbackArgs?: string;
  clientToken?: string;
  priority?: number;
}

export interface EnhanceForStartExecutionInput {
  modules?: ModuleForStartExecutionInput[];
  moeEnhance?: MoeEnhanceForStartExecutionInput;
  type?: string;
}

export interface InputForStartExecutionInput {
  type?: string;
  vid?: string;
}

export interface ModuleForStartExecutionInput {
  type?: string;
}

export interface MoeEnhanceForStartExecutionInput {
  config?: string;
  target?: TargetForStartExecutionInput;
  videoStrategy?: VideoStrategyForStartExecutionInput;
}

export interface OperationForStartExecutionInput {
  task?: TaskForStartExecutionInput;
  type?: string;
}

export interface TargetForStartExecutionInput {
  bitrate?: number;
  fps?: number;
  res?: string;
  resLimit?: number;
  scaleRatio?: number;
}

export interface TaskForStartExecutionInput {
  enhance?: EnhanceForStartExecutionInput;
  type?: string;
}

export interface VideoStrategyForStartExecutionInput {
  repairStrength?: number;
  repairStyle?: number;
}
