// GENERATED by packages/vod/scripts/gen-models.py from the BytePlus Python
// SDK (byteplussdkvod20250701 attribute_map + swagger_types). Do not edit by
// hand; re-run the generator. Enforces decision 0100 (wire is PascalCase,
// keep everything, no passthrough).

import type { ModelMeta } from "@byteplus-sdk/core";

export const startExecutionMetas: Record<string, ModelMeta> = {
  StartExecutionRequest: {
    attributeMap: { control: "Control", input: "Input", operation: "Operation" },
    swaggerTypes: { control: "ControlForStartExecutionInput", input: "InputForStartExecutionInput", operation: "OperationForStartExecutionInput" },
  },
  StartExecutionResponse: {
    attributeMap: { runId: "RunId" },
    swaggerTypes: { runId: "str" },
  },
  ControlForStartExecutionInput: {
    attributeMap: { callbackArgs: "CallbackArgs", clientToken: "ClientToken", priority: "Priority" },
    swaggerTypes: { callbackArgs: "str", clientToken: "str", priority: "int" },
  },
  EnhanceForStartExecutionInput: {
    attributeMap: { modules: "Modules", moeEnhance: "MoeEnhance", type: "Type" },
    swaggerTypes: { modules: "list[ModuleForStartExecutionInput]", moeEnhance: "MoeEnhanceForStartExecutionInput", type: "str" },
  },
  InputForStartExecutionInput: {
    attributeMap: { type: "Type", vid: "Vid" },
    swaggerTypes: { type: "str", vid: "str" },
  },
  ModuleForStartExecutionInput: {
    attributeMap: { type: "Type" },
    swaggerTypes: { type: "str" },
  },
  MoeEnhanceForStartExecutionInput: {
    attributeMap: { config: "Config", target: "Target", videoStrategy: "VideoStrategy" },
    swaggerTypes: { config: "str", target: "TargetForStartExecutionInput", videoStrategy: "VideoStrategyForStartExecutionInput" },
  },
  OperationForStartExecutionInput: {
    attributeMap: { task: "Task", type: "Type" },
    swaggerTypes: { task: "TaskForStartExecutionInput", type: "str" },
  },
  TargetForStartExecutionInput: {
    attributeMap: { bitrate: "Bitrate", fps: "Fps", res: "Res", resLimit: "ResLimit", scaleRatio: "ScaleRatio" },
    swaggerTypes: { bitrate: "int", fps: "float", res: "str", resLimit: "int", scaleRatio: "float" },
  },
  TaskForStartExecutionInput: {
    attributeMap: { enhance: "Enhance", type: "Type" },
    swaggerTypes: { enhance: "EnhanceForStartExecutionInput", type: "str" },
  },
  VideoStrategyForStartExecutionInput: {
    attributeMap: { repairStrength: "RepairStrength", repairStyle: "RepairStyle" },
    swaggerTypes: { repairStrength: "int", repairStyle: "int" },
  },
};
