#!/usr/bin/env python3
# coding: utf-8
"""Generate the VOD TS model interfaces + registered ModelMeta from the
authoritative Python SDK model files (`attribute_map` + `swagger_types`).

Enforces decision 0100: wire is PascalCase, keep everything, no passthrough.
Every Python model is ported faithfully; nested refs / list[...] recurse.

Usage:
    BYTEPLUS_PY_SDK=/path/to/byteplus-python-sdk-v2 \\
        python3 packages/vod/scripts/gen-models.py

Writes (relative to packages/vod/src/models/):
    start-execution.ts        input-tree interfaces
    start-execution-metas.ts  input-tree ModelMeta record
    get-execution.ts          output-tree interfaces
    get-execution-metas.ts    output-tree ModelMeta record
"""
import ast, os, sys, re

DEFAULT_SDK = (
    "/private/tmp/claude-501/-Users-longlh-orca-projects-byteplus-nodejs-sdk-v2/"
    "8f428543-1791-4daf-af46-8b9e5d5f4f1d/scratchpad/bp-py"
)
sdk = os.environ.get("BYTEPLUS_PY_SDK", DEFAULT_SDK)
MODELS_DIR = os.path.join(sdk, "byteplussdkvod20250701", "models")
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "models")


def parse_models():
    models = {}
    for fn in sorted(os.listdir(MODELS_DIR)):
        if not fn.endswith(".py") or fn == "__init__.py":
            continue
        tree = ast.parse(open(os.path.join(MODELS_DIR, fn)).read())
        for cls in [n for n in tree.body if isinstance(n, ast.ClassDef)]:
            am = st = None
            for stmt in cls.body:
                if isinstance(stmt, ast.Assign):
                    for t in stmt.targets:
                        if isinstance(t, ast.Name) and t.id == "attribute_map":
                            am = ast.literal_eval(stmt.value)
                        if isinstance(t, ast.Name) and t.id == "swagger_types":
                            st = ast.literal_eval(stmt.value)
            if am is not None and st is not None:
                models[cls.name] = {"attribute_map": am, "swagger_types": st}
    return models


def camel(snake):
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


PRIMITIVE = {"str": "string", "int": "number", "float": "number", "bool": "boolean"}


def ts_type(py_type):
    if py_type.startswith("list[") and py_type.endswith("]"):
        return ts_type(py_type[5:-1]) + "[]"
    return PRIMITIVE.get(py_type, py_type)  # model names pass through


def js_key(name):
    return name if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", name) else f'"{name}"'


def gen_interface(name, model):
    st = model["swagger_types"]
    lines = [f"export interface {name} {{"]
    for attr, py_type in st.items():
        field = camel(attr)
        required = name == "GetExecutionRequest" and field == "runId"
        opt = "" if required else "?"
        lines.append(f"  {js_key(field)}{opt}: {ts_type(py_type)};")
    lines.append("}")
    return "\n".join(lines)


def gen_meta(name, model):
    am, st = model["attribute_map"], model["swagger_types"]
    amp = ", ".join(f"{js_key(camel(k))}: {json_str(v)}" for k, v in am.items())
    stp = ", ".join(f"{js_key(camel(k))}: {json_str(v)}" for k, v in st.items())
    return (
        f"  {name}: {{\n"
        f"    attributeMap: {{ {amp} }},\n"
        f"    swaggerTypes: {{ {stp} }},\n"
        f"  }},"
    )


def json_str(s):
    return '"' + s.replace('"', '\\"') + '"'


HEADER = (
    "// GENERATED by packages/vod/scripts/gen-models.py from the BytePlus Python\n"
    "// SDK (byteplussdkvod20250701 attribute_map + swagger_types). Do not edit by\n"
    "// hand; re-run the generator. Enforces decision 0100 (wire is PascalCase,\n"
    "// keep everything, no passthrough).\n"
)


def write(path, body):
    with open(os.path.join(OUT_DIR, path), "w") as f:
        f.write(body)
    n = body.count("\n") + 1
    print(f"wrote {path} ({n} lines)")
    if n >= 200:
        sys.exit(f"ERROR: {path} has {n} lines (>= 200)")


def is_input(name):
    return name.endswith("ForStartExecutionInput") or name in ("StartExecutionRequest", "StartExecutionResponse")


def emit_group(names, models, iface_file, metas_file, metas_const):
    ifaces = HEADER + "\n" + "\n\n".join(gen_interface(n, models[n]) for n in names) + "\n"
    write(iface_file, ifaces)
    metas = HEADER + '\nimport type { ModelMeta } from "@byteplus-sdk/core";\n\n'
    metas += f"export const {metas_const}: Record<string, ModelMeta> = {{\n"
    metas += "\n".join(gen_meta(n, models[n]) for n in names)
    metas += "\n};\n"
    write(metas_file, metas)


def main():
    models = parse_models()
    inputs = [n for n in models if is_input(n)]
    outputs = [n for n in models if not is_input(n)]
    # stable, readable order: wrappers first, then the tree alphabetically
    def order(names, wrappers):
        w = [n for n in wrappers if n in names]
        rest = sorted(n for n in names if n not in wrappers)
        return w + rest
    inputs = order(inputs, ["StartExecutionRequest", "StartExecutionResponse"])
    outputs = order(outputs, ["GetExecutionRequest", "GetExecutionResponse"])
    emit_group(inputs, models, "start-execution.ts", "start-execution-metas.ts", "startExecutionMetas")
    emit_group(outputs, models, "get-execution.ts", "get-execution-metas.ts", "getExecutionMetas")
    print(f"total models: {len(models)} (input={len(inputs)}, output={len(outputs)})")


if __name__ == "__main__":
    main()
